### ISSUE TITLE
ingin menjadi developer

### ISSUE THREAD

**Issue by dhanyn10** [pascalalfadian/smartpublictransport#8]
saya ingin ikut mengambangkan aplikasi kiri.travel kak, bagaimana cara untuk berpartisipasi? kemudian apa saja yang harus dipalajari untuk kepentingan pengembangannya? terimakasih 😄

**Comment by pascalalfadian** [comment]
Hai @dhanyn10 thanks a lot ya sudah tertarik! Boleh2.. Terus terang project ini dulu memang dibuat open source, tetapi tidak saya siapkan khusus untuk hal2 tersebut, jadi saya juga masih belajar 😄. Mungkin kita bisa coba seperti ini:

1. Sorry ini ternyata project lama, dan harusnya sudah dihapus. Project yang lebih updated ada di [sini](https://github.com/projectkiri/smartpublictransport-as). Nah, kalau mau, Dhany bisa coba (fork and) clone project tersebut, dan coba setup di komputer sendiri. Kalau ada kesulitan bisa buka issue di sana.
2. Kalau ada saran pengembangan, baiknya buka issue dulu ya, supaya kita bisa diskusikan dulu apakah pengembangannya sesuai dengan visi misi project ini di awal. Kalau sudah oke, baru nanti Dhany sebaiknya buka pull request.

Kira2 begitu. Kalau ada yang kurang jelas, silahkan ditanyakan, tapi kalau sudah siap mohon close issue ini ya, dan setelah itu project ini saya mau hapus supaya tidak membingungkan.

Thanks;
Pascal

**Comment by dhanyn10** [comment]
mungkin sebaiknya di bagian readme ada keterangan tentang migrasi projectnya kak, beserta link ke project yang baru.
